# get patients, birthdate, birth time
PREFIX pcornet: <http://purl.obolibrary.org/obo/PCORnet/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

SELECT ?organism ?birth_date ?birth_time
#SELECT  ?organism ?neonate_stage ?start_of_neonate_stage ?instant_t1 ?birth_date ?birth_time
 
{
        GRAPH <virtual://PCORowl>
        {
		?organism a obo:NCBITaxon_9606 .
		# participates in 
		?organism obo:RO_0000056 ?neonate_stage .
		?neonate_stage a obo:UBERON_0000105 .
		?start_of_neonate_stage a obo:UBERON_0035946 .
		?start_of_neonate_stage obo:BFO_0000139 ?neonate_stage .
		# 0d temporal region
		?start_of_neonate_stage obo:BFO_0000155 ?instant_t1 .
		?instant_t1 a obo:BFO_0000048 .
		# 1D temporal region
		?tr3 a obo:BFO_0000038 .
		?instant_t1 obo:BFO_0000139 ?tr3 .
		?instant_t1 rdfs:label ?birth_time .
		?tr3 rdfs:label ?birth_date .
        }
}
