# select all non-hispanic, both identity datums, EIP, ETL
PREFIX pcornet: <http://purl.obolibrary.org/obo/PCORnet/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

SELECT ?person ?hlid ?pnhid ?etl ?ethnic_identification_process 
{
        GRAPH <virtual://PCORowl>
        {
		?hlid 	a 	obo:OMRSE_00000128;
			obo:IAO_0000136 ?person;
			obo:OBI_0000925 ?etl;
			obo:OBI_0000312 ?ethnic_identification_process .
		?pnhid	obo:OBI_0000312 ?etl .
		
				
        }
}
ORDER BY ?person
LIMIT 100
