# get URIs for PATIDs and actual PATID
PREFIX pcornet: <http://purl.obolibrary.org/obo/PCORnet/>
PREFIX bfo: <http://purl.obolibrary.org/obo/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?patientspatid ?patid ?patid_text
{
	GRAPH <virtual://PCORowl>
	{
		# PCORnet_00000019 'patient identifier'
		?patientspatid a pcornet:PCORnet_00000019 .
		# BFO_0000051 has_part
		?patientspatid bfo:BFO_0000051 ?patid .
		?patid a bfo:IAO_0000028 .
		?patid rdfs:label ?patid_text .
	}
}
ORDER BY ?patientspatid
